/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AppRouteImport } from './routes/app'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPassRouteImport } from './routes/app.pass'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppTrainRouteImport } from './routes/app.train'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachAttendanceRouteImport } from './routes/coach.attendance'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskAtRiskRouteImport } from './routes/desk.at-risk'
import { Route as DeskClassesRouteImport } from './routes/desk.classes'
import { Route as DeskCourtsRouteImport } from './routes/desk.courts'
import { Route as DeskGateRouteImport } from './routes/desk.gate'
import { Route as DeskGearRouteImport } from './routes/desk.gear'
import { Route as DeskPaymentsRouteImport } from './routes/desk.payments'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerAttendanceRouteImport } from './routes/manager.attendance'
import { Route as ManagerAuditRouteImport } from './routes/manager.audit'
import { Route as ManagerClassesRouteImport } from './routes/manager.classes'
import { Route as ManagerMembersRouteImport } from './routes/manager.members'
import { Route as ManagerPlansRouteImport } from './routes/manager.plans'
import { Route as ManagerPricesRouteImport } from './routes/manager.prices'
import { Route as ManagerPromosRouteImport } from './routes/manager.promos'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as ManagerStaffRouteImport } from './routes/manager.staff'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as V1SplatRouteImport } from './routes/v1.$'
import { Route as CoachStudentIdRouteImport } from './routes/coach.student.$id'
import { Route as DeskMemberIdRouteImport } from './routes/desk.member.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPassRoute = AppPassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAttendanceRoute = CoachAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => CoachRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAtRiskRoute = DeskAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => DeskRoute,
} as any)
const DeskClassesRoute = DeskClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCourtsRoute = DeskCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => DeskRoute,
} as any)
const DeskGateRoute = DeskGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => DeskRoute,
} as any)
const DeskGearRoute = DeskGearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPaymentsRoute = DeskPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DeskRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAttendanceRoute = ManagerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAuditRoute = ManagerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerClassesRoute = ManagerClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerMembersRoute = ManagerMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPlansRoute = ManagerPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPricesRoute = ManagerPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPromosRoute = ManagerPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerStaffRoute = ManagerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManagerRoute,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachStudentIdRoute = CoachStudentIdRouteImport.update({
  id: '/student/$id',
  path: '/student/$id',
  getParentRoute: () => CoachRoute,
} as any)
const DeskMemberIdRoute = DeskMemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pass': typeof AppPassRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/desk/at-risk': typeof DeskAtRiskRoute
  '/desk/classes': typeof DeskClassesRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gate': typeof DeskGateRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/members': typeof ManagerMembersRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/promos': typeof ManagerPromosRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/coach/student/$id': typeof CoachStudentIdRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pass': typeof AppPassRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/desk/at-risk': typeof DeskAtRiskRoute
  '/desk/classes': typeof DeskClassesRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gate': typeof DeskGateRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/members': typeof ManagerMembersRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/promos': typeof ManagerPromosRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app': typeof AppIndexRoute
  '/coach': typeof CoachIndexRoute
  '/desk': typeof DeskIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/coach/student/$id': typeof CoachStudentIdRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pass': typeof AppPassRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/coach/attendance': typeof CoachAttendanceRoute
  '/desk/at-risk': typeof DeskAtRiskRoute
  '/desk/classes': typeof DeskClassesRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gate': typeof DeskGateRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/members': typeof ManagerMembersRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/promos': typeof ManagerPromosRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/coach/student/$id': typeof CoachStudentIdRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts'
    | '/app'
    | '/coach'
    | '/desk'
    | '/forgot'
    | '/login'
    | '/manager'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/notifications'
    | '/app/pass'
    | '/app/plans'
    | '/app/train'
    | '/coach/attendance'
    | '/desk/at-risk'
    | '/desk/classes'
    | '/desk/courts'
    | '/desk/gate'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/attendance'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/members'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/promos'
    | '/manager/settings'
    | '/manager/staff'
    | '/pay/return'
    | '/v1/$'
    | '/app/'
    | '/coach/'
    | '/desk/'
    | '/manager/'
    | '/coach/student/$id'
    | '/desk/member/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts'
    | '/forgot'
    | '/login'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/notifications'
    | '/app/pass'
    | '/app/plans'
    | '/app/train'
    | '/coach/attendance'
    | '/desk/at-risk'
    | '/desk/classes'
    | '/desk/courts'
    | '/desk/gate'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/attendance'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/members'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/promos'
    | '/manager/settings'
    | '/manager/staff'
    | '/pay/return'
    | '/v1/$'
    | '/app'
    | '/coach'
    | '/desk'
    | '/manager'
    | '/coach/student/$id'
    | '/desk/member/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts'
    | '/app'
    | '/coach'
    | '/desk'
    | '/forgot'
    | '/login'
    | '/manager'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/notifications'
    | '/app/pass'
    | '/app/plans'
    | '/app/train'
    | '/coach/attendance'
    | '/desk/at-risk'
    | '/desk/classes'
    | '/desk/courts'
    | '/desk/gate'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/attendance'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/members'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/promos'
    | '/manager/settings'
    | '/manager/staff'
    | '/pay/return'
    | '/v1/$'
    | '/app/'
    | '/coach/'
    | '/desk/'
    | '/manager/'
    | '/coach/student/$id'
    | '/desk/member/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsRoute: typeof AlertsRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  DeskRoute: typeof DeskRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  PayReturnRoute: typeof PayReturnRoute
  V1SplatRoute: typeof V1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pass': {
      id: '/app/pass'
      path: '/pass'
      fullPath: '/app/pass'
      preLoaderRoute: typeof AppPassRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/train': {
      id: '/app/train'
      path: '/train'
      fullPath: '/app/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/attendance': {
      id: '/coach/attendance'
      path: '/attendance'
      fullPath: '/coach/attendance'
      preLoaderRoute: typeof CoachAttendanceRouteImport
      parentRoute: typeof CoachRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/at-risk': {
      id: '/desk/at-risk'
      path: '/at-risk'
      fullPath: '/desk/at-risk'
      preLoaderRoute: typeof DeskAtRiskRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/classes': {
      id: '/desk/classes'
      path: '/classes'
      fullPath: '/desk/classes'
      preLoaderRoute: typeof DeskClassesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/courts': {
      id: '/desk/courts'
      path: '/courts'
      fullPath: '/desk/courts'
      preLoaderRoute: typeof DeskCourtsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/gate': {
      id: '/desk/gate'
      path: '/gate'
      fullPath: '/desk/gate'
      preLoaderRoute: typeof DeskGateRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/gear': {
      id: '/desk/gear'
      path: '/gear'
      fullPath: '/desk/gear'
      preLoaderRoute: typeof DeskGearRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/payments': {
      id: '/desk/payments'
      path: '/payments'
      fullPath: '/desk/payments'
      preLoaderRoute: typeof DeskPaymentsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/attendance': {
      id: '/manager/attendance'
      path: '/attendance'
      fullPath: '/manager/attendance'
      preLoaderRoute: typeof ManagerAttendanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/audit': {
      id: '/manager/audit'
      path: '/audit'
      fullPath: '/manager/audit'
      preLoaderRoute: typeof ManagerAuditRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/classes': {
      id: '/manager/classes'
      path: '/classes'
      fullPath: '/manager/classes'
      preLoaderRoute: typeof ManagerClassesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/members': {
      id: '/manager/members'
      path: '/members'
      fullPath: '/manager/members'
      preLoaderRoute: typeof ManagerMembersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/plans': {
      id: '/manager/plans'
      path: '/plans'
      fullPath: '/manager/plans'
      preLoaderRoute: typeof ManagerPlansRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/prices': {
      id: '/manager/prices'
      path: '/prices'
      fullPath: '/manager/prices'
      preLoaderRoute: typeof ManagerPricesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/promos': {
      id: '/manager/promos'
      path: '/promos'
      fullPath: '/manager/promos'
      preLoaderRoute: typeof ManagerPromosRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/staff': {
      id: '/manager/staff'
      path: '/staff'
      fullPath: '/manager/staff'
      preLoaderRoute: typeof ManagerStaffRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/student/$id': {
      id: '/coach/student/$id'
      path: '/student/$id'
      fullPath: '/coach/student/$id'
      preLoaderRoute: typeof CoachStudentIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/desk/member/$id': {
      id: '/desk/member/$id'
      path: '/member/$id'
      fullPath: '/desk/member/$id'
      preLoaderRoute: typeof DeskMemberIdRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppBookRoute: typeof AppBookRoute
  AppClassesRoute: typeof AppClassesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPassRoute: typeof AppPassRoute
  AppPlansRoute: typeof AppPlansRoute
  AppTrainRoute: typeof AppTrainRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppBookRoute: AppBookRoute,
  AppClassesRoute: AppClassesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPassRoute: AppPassRoute,
  AppPlansRoute: AppPlansRoute,
  AppTrainRoute: AppTrainRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachRouteChildren {
  CoachAttendanceRoute: typeof CoachAttendanceRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachStudentIdRoute: typeof CoachStudentIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAttendanceRoute: CoachAttendanceRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachStudentIdRoute: CoachStudentIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface DeskRouteChildren {
  DeskAtRiskRoute: typeof DeskAtRiskRoute
  DeskClassesRoute: typeof DeskClassesRoute
  DeskCourtsRoute: typeof DeskCourtsRoute
  DeskGateRoute: typeof DeskGateRoute
  DeskGearRoute: typeof DeskGearRoute
  DeskPaymentsRoute: typeof DeskPaymentsRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskMemberIdRoute: typeof DeskMemberIdRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskAtRiskRoute: DeskAtRiskRoute,
  DeskClassesRoute: DeskClassesRoute,
  DeskCourtsRoute: DeskCourtsRoute,
  DeskGateRoute: DeskGateRoute,
  DeskGearRoute: DeskGearRoute,
  DeskPaymentsRoute: DeskPaymentsRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskMemberIdRoute: DeskMemberIdRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface ManagerRouteChildren {
  ManagerAttendanceRoute: typeof ManagerAttendanceRoute
  ManagerAuditRoute: typeof ManagerAuditRoute
  ManagerClassesRoute: typeof ManagerClassesRoute
  ManagerMembersRoute: typeof ManagerMembersRoute
  ManagerPlansRoute: typeof ManagerPlansRoute
  ManagerPricesRoute: typeof ManagerPricesRoute
  ManagerPromosRoute: typeof ManagerPromosRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerStaffRoute: typeof ManagerStaffRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAttendanceRoute: ManagerAttendanceRoute,
  ManagerAuditRoute: ManagerAuditRoute,
  ManagerClassesRoute: ManagerClassesRoute,
  ManagerMembersRoute: ManagerMembersRoute,
  ManagerPlansRoute: ManagerPlansRoute,
  ManagerPricesRoute: ManagerPricesRoute,
  ManagerPromosRoute: ManagerPromosRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerStaffRoute: ManagerStaffRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsRoute: AlertsRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  DeskRoute: DeskRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  PayReturnRoute: PayReturnRoute,
  V1SplatRoute: V1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
