/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteImport } from './routes/app'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppTrainRouteImport } from './routes/app.train'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskCourtsRouteImport } from './routes/desk.courts'
import { Route as DeskGearRouteImport } from './routes/desk.gear'
import { Route as DeskPaymentsRouteImport } from './routes/desk.payments'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerAuditRouteImport } from './routes/manager.audit'
import { Route as ManagerClassesRouteImport } from './routes/manager.classes'
import { Route as ManagerPlansRouteImport } from './routes/manager.plans'
import { Route as ManagerPricesRouteImport } from './routes/manager.prices'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as V1SplatRouteImport } from './routes/v1.$'
import { Route as DeskMemberIdRouteImport } from './routes/desk.member.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCourtsRoute = DeskCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => DeskRoute,
} as any)
const DeskGearRoute = DeskGearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPaymentsRoute = DeskPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DeskRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAuditRoute = ManagerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerClassesRoute = ManagerClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPlansRoute = ManagerPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPricesRoute = ManagerPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRoute,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskMemberIdRoute = DeskMemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app/': typeof AppIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/coach': typeof CoachRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app': typeof AppIndexRoute
  '/desk': typeof DeskIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/book': typeof AppBookRoute
  '/app/classes': typeof AppClassesRoute
  '/app/plans': typeof AppPlansRoute
  '/app/train': typeof AppTrainRoute
  '/desk/courts': typeof DeskCourtsRoute
  '/desk/gear': typeof DeskGearRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/manager/audit': typeof ManagerAuditRoute
  '/manager/classes': typeof ManagerClassesRoute
  '/manager/plans': typeof ManagerPlansRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/pay/return': typeof PayReturnRoute
  '/v1/$': typeof V1SplatRoute
  '/app/': typeof AppIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/desk/member/$id': typeof DeskMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/coach'
    | '/desk'
    | '/forgot'
    | '/login'
    | '/manager'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/plans'
    | '/app/train'
    | '/desk/courts'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/settings'
    | '/pay/return'
    | '/v1/$'
    | '/app/'
    | '/desk/'
    | '/manager/'
    | '/desk/member/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/coach'
    | '/forgot'
    | '/login'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/plans'
    | '/app/train'
    | '/desk/courts'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/settings'
    | '/pay/return'
    | '/v1/$'
    | '/app'
    | '/desk'
    | '/manager'
    | '/desk/member/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/coach'
    | '/desk'
    | '/forgot'
    | '/login'
    | '/manager'
    | '/register'
    | '/app/assistant'
    | '/app/book'
    | '/app/classes'
    | '/app/plans'
    | '/app/train'
    | '/desk/courts'
    | '/desk/gear'
    | '/desk/payments'
    | '/manager/audit'
    | '/manager/classes'
    | '/manager/plans'
    | '/manager/prices'
    | '/manager/settings'
    | '/pay/return'
    | '/v1/$'
    | '/app/'
    | '/desk/'
    | '/manager/'
    | '/desk/member/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRoute
  DeskRoute: typeof DeskRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  PayReturnRoute: typeof PayReturnRoute
  V1SplatRoute: typeof V1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/train': {
      id: '/app/train'
      path: '/train'
      fullPath: '/app/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/courts': {
      id: '/desk/courts'
      path: '/courts'
      fullPath: '/desk/courts'
      preLoaderRoute: typeof DeskCourtsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/gear': {
      id: '/desk/gear'
      path: '/gear'
      fullPath: '/desk/gear'
      preLoaderRoute: typeof DeskGearRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/payments': {
      id: '/desk/payments'
      path: '/payments'
      fullPath: '/desk/payments'
      preLoaderRoute: typeof DeskPaymentsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/audit': {
      id: '/manager/audit'
      path: '/audit'
      fullPath: '/manager/audit'
      preLoaderRoute: typeof ManagerAuditRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/classes': {
      id: '/manager/classes'
      path: '/classes'
      fullPath: '/manager/classes'
      preLoaderRoute: typeof ManagerClassesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/plans': {
      id: '/manager/plans'
      path: '/plans'
      fullPath: '/manager/plans'
      preLoaderRoute: typeof ManagerPlansRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/prices': {
      id: '/manager/prices'
      path: '/prices'
      fullPath: '/manager/prices'
      preLoaderRoute: typeof ManagerPricesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/member/$id': {
      id: '/desk/member/$id'
      path: '/member/$id'
      fullPath: '/desk/member/$id'
      preLoaderRoute: typeof DeskMemberIdRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppBookRoute: typeof AppBookRoute
  AppClassesRoute: typeof AppClassesRoute
  AppPlansRoute: typeof AppPlansRoute
  AppTrainRoute: typeof AppTrainRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppBookRoute: AppBookRoute,
  AppClassesRoute: AppClassesRoute,
  AppPlansRoute: AppPlansRoute,
  AppTrainRoute: AppTrainRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DeskRouteChildren {
  DeskCourtsRoute: typeof DeskCourtsRoute
  DeskGearRoute: typeof DeskGearRoute
  DeskPaymentsRoute: typeof DeskPaymentsRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskMemberIdRoute: typeof DeskMemberIdRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskCourtsRoute: DeskCourtsRoute,
  DeskGearRoute: DeskGearRoute,
  DeskPaymentsRoute: DeskPaymentsRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskMemberIdRoute: DeskMemberIdRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface ManagerRouteChildren {
  ManagerAuditRoute: typeof ManagerAuditRoute
  ManagerClassesRoute: typeof ManagerClassesRoute
  ManagerPlansRoute: typeof ManagerPlansRoute
  ManagerPricesRoute: typeof ManagerPricesRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAuditRoute: ManagerAuditRoute,
  ManagerClassesRoute: ManagerClassesRoute,
  ManagerPlansRoute: ManagerPlansRoute,
  ManagerPricesRoute: ManagerPricesRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRoute,
  DeskRoute: DeskRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  PayReturnRoute: PayReturnRoute,
  V1SplatRoute: V1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
